import "server-only";
import JSZip from "jszip";
import { PDFDocument } from "pdf-lib";
import { z } from "zod";
import { FINAL_EXPORTABLE } from "@/lib/domain/workflow";
import { type AuthContext, can } from "@/server/auth/current";
import { db } from "@/server/db";
import { forbidden, invalid } from "@/server/errors";
import { sha256 } from "@/server/security/crypto";
import { audit } from "@/server/services/audit";
import { exportPaperPdf } from "@/server/services/exports";
import { saveFile, signedAssetUrl } from "@/server/storage";
import { BRAND } from "@/lib/brand";

export const packageSchema = z.object({
  paperIds: z.array(z.string()).min(1, "Select at least one paper").max(200),
  format: z.enum(["zip", "batch", "print"]),
  label: z.string().trim().max(80).optional(),
});

/**
 * Build a printing package from locked papers. Every paper is rendered from its immutable FINAL
 * version (with per-downloader watermark), hashed, and listed in a manifest. The package itself is
 * stored encrypted and delivered through a short-lived signed URL.
 */
export async function buildPackage(ctx: AuthContext, raw: unknown) {
  if (!can(ctx, "paper.package") || !can(ctx, "paper.export.final")) throw forbidden("You are not authorised to package final papers.");
  const input = packageSchema.parse(raw);
  const papers = await db.questionPaper.findMany({
    where: { id: { in: input.paperIds }, deletedAt: null },
    include: { examination: { include: { course: { select: { code: true, title: true } }, session: { select: { code: true, name: true } }, schedule: true } } },
    orderBy: [{ examination: { schedule: { date: "asc" } } }, { code: "asc" }],
  });
  if (papers.length !== input.paperIds.length) throw invalid("Some selected papers are unavailable.");
  const notFinal = papers.filter((p) => !FINAL_EXPORTABLE.includes(p.status));
  if (notFinal.length) throw invalid(`Only locked papers can be packaged: ${notFinal.map((p) => p.code).join(", ")}`);

  const files: { name: string; pdf: Buffer; hash: string; paper: (typeof papers)[number] }[] = [];
  for (const p of papers) {
    const { pdf, hash } = await exportPaperPdf(ctx, p.id, "final", { skipAudit: true });
    const name = `${p.examination.course.code}${papers.filter((x) => x.examination.course.code === p.examination.course.code).length > 1 ? `-SET${p.setLabel}` : ""}.pdf`;
    files.push({ name, pdf, hash, paper: p });
  }
  const sessions = [...new Set(papers.map((p) => p.examination.session.name))];
  const title = input.label || sessions.join(" + ");
  const stamp = new Date().toISOString().replace(/[:T]/g, "-").slice(0, 16);

  let data: Buffer;
  let fileName: string;
  const merge = async () => {
    const out = await PDFDocument.create();
    out.setTitle(`${title} — printing batch`);
    out.setProducer(BRAND.name);
    for (const f of files) {
      const doc = await PDFDocument.load(f.pdf);
      const pages = await out.copyPages(doc, doc.getPageIndices());
      pages.forEach((pg) => out.addPage(pg));
    }
    return Buffer.from(await out.save());
  };
  const manifest = [
    `${BRAND.name} PRINTING PACKAGE — CONFIDENTIAL`,
    `Title:        ${title}`,
    `Generated:    ${new Date().toISOString()}`,
    `Generated by: ${ctx.user.name} (${ctx.user.employeeId})`,
    `Papers:       ${files.length}`,
    ``,
    `FILE                         EXAM DATE     VERSION HASH (paper)                                   SHA-256 (PDF)`,
    ...files.map((f) => `${f.name.padEnd(28)} ${f.paper.examination.schedule ? f.paper.examination.schedule.date.toISOString().slice(0, 10) : "—".padEnd(10)}    ${(f.paper.finalHash ?? "").slice(0, 16)}…  ${f.hash}`),
    ``,
    `Verify each file with: certutil -hashfile <file> SHA256   (Windows)  /  shasum -a 256 <file>  (macOS/Linux)`,
  ].join("\n");

  if (input.format === "batch") {
    data = await merge();
    fileName = `${stamp}-batch.pdf`;
  } else {
    const zip = new JSZip();
    const folder = zip.folder(title.replace(/[^\w .+-]/g, "_").toUpperCase())!;
    for (const f of files) folder.file(f.name, f.pdf);
    folder.file("MANIFEST.txt", manifest);
    if (input.format === "print") {
      folder.file("_BATCH-ALL-PAPERS.pdf", await merge());
      folder.file(
        "PRINTING-INSTRUCTIONS.txt",
        [
          "1. Print only on the secure press/printer designated by the Controller of Examinations.",
          "2. Verify every file's SHA-256 against MANIFEST.txt before printing.",
          "3. Count and seal printed copies per examination date and slot; record counts in the dispatch register.",
          "4. Destroy spoilt copies under supervision. Do not retain electronic copies after printing.",
        ].join("\n"),
      );
    }
    data = Buffer.from(await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" }));
    fileName = `${stamp}-${input.format === "print" ? "printing-package" : "papers"}.zip`;
  }

  const asset = await saveFile({ data, name: fileName, kind: "PACKAGE", ownerId: ctx.user.id });
  await audit({
    actorId: ctx.user.id,
    actorName: ctx.user.name,
    action: "paper.package",
    resourceType: "package",
    resourceId: asset.id,
    summary: `${input.format.toUpperCase()} package of ${files.length} paper(s): ${files.map((f) => f.paper.code).join(", ")}`,
    metadata: { sha256: sha256(data), papers: files.map((f) => ({ id: f.paper.id, code: f.paper.code, sha256: f.hash })) },
  });
  return { url: signedAssetUrl(asset.id, 300, "attachment"), fileName, count: files.length, bytes: data.length };
}
