/* Realistic demo question banks. Format: [unit, topicIndex, marks, difficulty, bloom, type, CO, text] */
import type { BloomLevel, Difficulty, QuestionType } from "../../src/generated/prisma/enums";

export type Q = [number, number, number, "E" | "M" | "H", "R" | "U" | "Ap" | "An" | "Ev" | "C", QuestionType, string, string];

export const D: Record<"E" | "M" | "H", Difficulty> = { E: "EASY", M: "MODERATE", H: "HARD" };
export const B: Record<Q[4], BloomLevel> = {
  R: "REMEMBER",
  U: "UNDERSTAND",
  Ap: "APPLY",
  An: "ANALYZE",
  Ev: "EVALUATE",
  C: "CREATE",
};

export interface CourseBank {
  units: { title: string; topics: string[] }[];
  outcomes: [string, string, BloomLevel][];
  questions: Q[];
}

// ───────────────────────── BCS301 Data Structures ─────────────────────────
export const DATA_STRUCTURES: CourseBank = {
  units: [
    { title: "Introduction and Arrays", topics: ["Classification of data structures", "Algorithm analysis", "Array representation"] },
    { title: "Stacks and Queues", topics: ["Stack operations", "Expression conversion", "Queue variants"] },
    { title: "Linked Lists", topics: ["Singly linked lists", "Doubly and circular lists", "Applications of lists"] },
    { title: "Trees", topics: ["Binary trees and traversal", "Binary search trees", "Balanced trees"] },
    { title: "Graphs, Searching and Sorting", topics: ["Graph representation and traversal", "Sorting algorithms", "Searching and hashing"] },
  ],
  outcomes: [
    ["CO1", "Explain fundamental data structures and analyse algorithm complexity", "UNDERSTAND"],
    ["CO2", "Apply stacks and queues to solve computational problems", "APPLY"],
    ["CO3", "Implement operations on linked lists", "APPLY"],
    ["CO4", "Analyse tree structures and their operations", "ANALYZE"],
    ["CO5", "Evaluate graph, searching and sorting algorithms", "EVALUATE"],
  ],
  questions: [
    // 2 marks
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "Define a data structure. Give two examples of linear data structures."],
    [1, 2, 2, "E", "U", "VERY_SHORT", "CO1", "What is the time complexity of accessing an array element by its index? Justify briefly."],
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "Distinguish between primitive and non-primitive data structures."],
    [1, 1, 2, "E", "R", "VERY_SHORT", "CO1", "What is meant by asymptotic notation?"],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "Define a stack and state its LIFO property."],
    [2, 2, 2, "E", "R", "VERY_SHORT", "CO2", "What is a circular queue?"],
    [2, 1, 2, "E", "Ap", "SHORT", "CO2", "Convert the infix expression $A + B * C$ to postfix form."],
    [2, 2, 2, "E", "R", "VERY_SHORT", "CO2", "List any two applications of queues in computing."],
    [3, 0, 2, "E", "R", "VERY_SHORT", "CO3", "What is a self-referential structure?"],
    [3, 0, 2, "E", "U", "VERY_SHORT", "CO3", "Mention two advantages of linked lists over arrays."],
    [3, 1, 2, "E", "R", "VERY_SHORT", "CO3", "What is a header node in a linked list?"],
    [4, 1, 2, "E", "R", "VERY_SHORT", "CO4", "Define a binary search tree."],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "What is the height of a tree? Illustrate with a small example."],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "Define a complete binary tree."],
    [4, 2, 2, "E", "U", "VERY_SHORT", "CO4", "What is the balance factor of a node in an AVL tree?"],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "Define a graph and its adjacency matrix representation."],
    [5, 2, 2, "E", "R", "VERY_SHORT", "CO5", "What is hashing?"],
    [5, 2, 2, "E", "R", "VERY_SHORT", "CO5", "What is a collision in hashing?"],
    [5, 1, 2, "E", "U", "VERY_SHORT", "CO5", "State the best-case time complexity of insertion sort and when it occurs."],
    [2, 0, 2, "E", "U", "VERY_SHORT", "CO2", "What is stack overflow? When does it occur?"],
    [3, 1, 2, "E", "R", "VERY_SHORT", "CO3", "What is a doubly linked list?"],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "Define a leaf node and an internal node of a tree."],
    [5, 1, 2, "E", "R", "VERY_SHORT", "CO5", "What is a stable sorting algorithm? Give one example."],
    [1, 1, 2, "E", "U", "VERY_SHORT", "CO1", "What is the space complexity of an algorithm?"],
    // 5 marks
    [1, 1, 5, "M", "U", "DESCRIPTIVE", "CO1", "Explain the Big-O, Big-Omega and Big-Theta notations with one example each."],
    [1, 2, 5, "E", "Ap", "PROBLEM", "CO1", "Write an algorithm to insert an element at a given position in an array and state its time complexity."],
    [1, 2, 5, "M", "Ap", "PROBLEM", "CO1", "Explain row-major and column-major representation of a two-dimensional array. Derive the address formula $Loc(A[i][j]) = Base + w \\times (n \\times i + j)$ for row-major order."],
    [2, 0, 5, "E", "Ap", "PROBLEM", "CO2", "Write algorithms for PUSH and POP operations on an array-based stack, handling overflow and underflow."],
    [2, 1, 5, "M", "Ap", "PROBLEM", "CO2", "Evaluate the postfix expression `6 2 3 + - 3 8 2 / + *`, showing the stack contents after each step."],
    [2, 2, 5, "M", "U", "DESCRIPTIVE", "CO2", "Explain the working of a circular queue with a suitable diagram and give the algorithm for insertion."],
    [2, 2, 5, "M", "U", "DESCRIPTIVE", "CO2", "Differentiate between a simple queue and a priority queue with examples."],
    [3, 0, 5, "M", "Ap", "PROBLEM", "CO3", "Write an algorithm to reverse a singly linked list in place."],
    [3, 1, 5, "M", "U", "DESCRIPTIVE", "CO3", "Explain insertion of a node at the beginning, middle and end of a doubly linked list."],
    [3, 2, 5, "M", "Ap", "PROBLEM", "CO3", "How can a polynomial be represented using a linked list? Illustrate with $5x^3 + 4x^2 + 2$."],
    [4, 0, 5, "E", "U", "DESCRIPTIVE", "CO4", "Explain inorder, preorder and postorder traversals with an example tree."],
    [4, 1, 5, "M", "Ap", "PROBLEM", "CO4", "Construct a binary search tree for the keys 45, 15, 79, 90, 10, 55, 12, 20, 50 and write its inorder traversal."],
    [4, 2, 5, "M", "U", "DESCRIPTIVE", "CO4", "Explain the four rotations used to rebalance an AVL tree."],
    [5, 2, 5, "M", "U", "DESCRIPTIVE", "CO5", "Explain linear probing and quadratic probing as collision resolution techniques."],
    [5, 2, 5, "E", "R", "DESCRIPTIVE", "CO5", "Write the binary search algorithm and state its time complexity."],
    [5, 0, 5, "M", "An", "DESCRIPTIVE", "CO5", "Compare breadth-first and depth-first traversal of a graph."],
    [1, 0, 5, "E", "R", "DESCRIPTIVE", "CO1", "List and briefly describe the basic operations performed on data structures."],
    // 10 marks
    [1, 0, 10, "M", "U", "ESSAY", "CO1", "Discuss the classification of data structures in detail. Explain the operations performed on each type with suitable examples."],
    [1, 1, 10, "H", "An", "PROBLEM", "CO1", "Analyse the time and space complexity of iterative and recursive algorithms that compute the $n^{th}$ Fibonacci number. Which approach would you recommend, and why?"],
    [2, 1, 10, "M", "Ap", "PROBLEM", "CO2", "Explain the algorithm to convert an infix expression to postfix using a stack. Convert $(A + B) * (C - D) / E$, tabulating the stack and output at each step."],
    [2, 0, 10, "H", "An", "PROBLEM", "CO2", "Implement a queue using two stacks. Write algorithms for enqueue and dequeue and analyse their amortised complexity."],
    [3, 1, 10, "M", "Ap", "PROBLEM", "CO3", "Write a menu-driven algorithm for a circular singly linked list supporting insertion, deletion and display. Discuss the advantages of circular lists."],
    [3, 2, 10, "H", "An", "DESCRIPTIVE", "CO3", "Compare arrays, singly linked lists and doubly linked lists in terms of memory, insertion, deletion and access cost. Justify with complexity analysis."],
    [4, 2, 10, "H", "Ap", "PROBLEM", "CO4", "Construct an AVL tree by inserting the keys 50, 20, 60, 10, 8, 15, 32, 46, 11, 48 in that order. Show the tree and the rotation applied after each imbalance."],
    [4, 1, 10, "M", "U", "DESCRIPTIVE", "CO4", "Explain deletion of a node from a binary search tree covering all three cases, with examples and an algorithm."],
    [5, 0, 10, "H", "Ap", "PROBLEM", "CO5", "Explain Dijkstra's shortest path algorithm and apply it from vertex A to the graph below.\n\n| Edge | Weight |\n|---|---|\n| A–B | 4 |\n| A–C | 2 |\n| B–C | 1 |\n| B–D | 5 |\n| C–D | 8 |\n| C–E | 10 |\n| D–E | 2 |"],
    [5, 1, 10, "M", "An", "PROBLEM", "CO5", "Sort 38, 27, 43, 3, 9, 82, 10 using merge sort and quick sort. Compare the two algorithms in terms of time complexity, stability and space usage."],
    [5, 2, 10, "H", "Ev", "ESSAY", "CO5", "Evaluate the suitability of hashing versus balanced search trees for implementing a compiler's symbol table."],
  ],
};

// ───────────────────────── BCS302 Database Management Systems ─────────────────────────
export const DBMS: CourseBank = {
  units: [
    { title: "Database Concepts and ER Modelling", topics: ["DBMS architecture", "Entity–relationship model", "Data independence"] },
    { title: "Relational Model and Algebra", topics: ["Keys and constraints", "Relational algebra", "Relational calculus"] },
    { title: "Structured Query Language", topics: ["DDL and DML", "Joins and subqueries", "Views and triggers"] },
    { title: "Normalisation", topics: ["Functional dependencies", "Normal forms", "Decomposition"] },
    { title: "Transactions and Concurrency", topics: ["ACID properties", "Concurrency control", "Recovery"] },
  ],
  outcomes: [
    ["CO1", "Describe database architecture and model data using ER diagrams", "UNDERSTAND"],
    ["CO2", "Formulate queries using relational algebra", "APPLY"],
    ["CO3", "Write SQL queries for data definition and manipulation", "APPLY"],
    ["CO4", "Normalise relations using functional dependencies", "ANALYZE"],
    ["CO5", "Evaluate transaction management and recovery techniques", "EVALUATE"],
  ],
  questions: [
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "Define a database management system."],
    [1, 2, 2, "E", "U", "VERY_SHORT", "CO1", "What is physical data independence?"],
    [1, 1, 2, "E", "R", "VERY_SHORT", "CO1", "What is a weak entity set? Give an example."],
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "List any two responsibilities of a database administrator."],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "Differentiate between a primary key and a candidate key."],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "What is referential integrity?"],
    [2, 1, 2, "E", "U", "SHORT", "CO2", "State the purpose of the projection operator $\\pi$ in relational algebra."],
    [2, 1, 2, "E", "R", "VERY_SHORT", "CO2", "Define the natural join operation."],
    [3, 0, 2, "E", "R", "VERY_SHORT", "CO3", "Distinguish between DELETE and TRUNCATE in SQL."],
    [3, 2, 2, "E", "R", "VERY_SHORT", "CO3", "What is a view in SQL?"],
    [3, 1, 2, "E", "U", "SHORT", "CO3", "Write an SQL query to display the second highest salary from an EMPLOYEE table."],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "Define functional dependency."],
    [4, 1, 2, "E", "R", "VERY_SHORT", "CO4", "When is a relation said to be in Second Normal Form?"],
    [4, 2, 2, "E", "U", "VERY_SHORT", "CO4", "What is a lossless-join decomposition?"],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "Expand ACID and state its significance."],
    [5, 1, 2, "E", "R", "VERY_SHORT", "CO5", "What is a deadlock?"],
    [5, 2, 2, "E", "R", "VERY_SHORT", "CO5", "What is a checkpoint in database recovery?"],
    [5, 1, 2, "E", "U", "VERY_SHORT", "CO5", "Define a conflict-serialisable schedule."],
    [1, 1, 2, "E", "R", "VERY_SHORT", "CO1", "What is a composite attribute? Give an example."],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "What is a foreign key?"],
    [3, 0, 2, "E", "R", "VERY_SHORT", "CO3", "What is the purpose of the GROUP BY clause?"],
    [4, 1, 2, "E", "U", "VERY_SHORT", "CO4", "What is a transitive dependency?"],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "What is a transaction?"],
    [1, 0, 5, "M", "U", "DESCRIPTIVE", "CO1", "Explain the three-schema architecture of a DBMS with a neat diagram."],
    [1, 1, 5, "M", "Ap", "PROBLEM", "CO1", "Draw an ER diagram for a university library with entities BOOK, MEMBER and LOAN. Indicate keys and cardinalities."],
    [1, 0, 5, "E", "R", "DESCRIPTIVE", "CO1", "List the advantages of a DBMS over a file-processing system."],
    [2, 1, 5, "M", "Ap", "PROBLEM", "CO2", "Given STUDENT(roll, name, dept) and ENROL(roll, course), write relational-algebra expressions to (a) list names of students enrolled in DBMS and (b) list students not enrolled in any course."],
    [2, 0, 5, "M", "U", "DESCRIPTIVE", "CO2", "Explain entity integrity and referential integrity constraints with examples."],
    [2, 2, 5, "M", "U", "DESCRIPTIVE", "CO2", "Differentiate between tuple relational calculus and domain relational calculus."],
    [3, 1, 5, "M", "Ap", "PROBLEM", "CO3", "Explain inner, left outer and full outer joins with SQL examples."],
    [3, 2, 5, "M", "Ap", "PROBLEM", "CO3", "Write an SQL trigger that records every salary change of an employee into a SALARY_AUDIT table."],
    [3, 0, 5, "E", "Ap", "PROBLEM", "CO3", "Write SQL statements to create a table ORDERS with a primary key, a foreign key to CUSTOMER and a CHECK constraint on the amount."],
    [4, 0, 5, "M", "Ap", "PROBLEM", "CO4", "Compute the closure of $\\{A, B\\}$ for R(A, B, C, D, E) with F = { A→C, B→D, CD→E }."],
    [4, 1, 5, "M", "U", "DESCRIPTIVE", "CO4", "Explain BCNF with an example and state how it differs from 3NF."],
    [5, 1, 5, "M", "U", "DESCRIPTIVE", "CO5", "Explain the two-phase locking protocol and its variants."],
    [5, 2, 5, "M", "U", "DESCRIPTIVE", "CO5", "Describe log-based recovery using deferred and immediate update."],
    [5, 1, 5, "M", "An", "PROBLEM", "CO5", "Test whether the schedule r1(X) r2(X) w1(X) w2(X) is conflict serialisable using a precedence graph."],
    [1, 1, 10, "M", "Ap", "PROBLEM", "CO1", "Design a complete ER model for a hospital management system covering patients, doctors, wards and treatments. Convert it into relational schemas."],
    [2, 1, 10, "M", "Ap", "PROBLEM", "CO2", "Explain the fundamental and additional operations of relational algebra with examples on a sample EMPLOYEE–DEPARTMENT database."],
    [3, 1, 10, "M", "Ap", "PROBLEM", "CO3", "Write SQL queries for the following on EMP(eno, ename, sal, dno) and DEPT(dno, dname): (a) department-wise average salary, (b) employees earning more than their department average, (c) departments without employees, (d) top three earners, (e) a view of employee name with department name."],
    [3, 2, 10, "H", "An", "DESCRIPTIVE", "CO3", "Analyse the role of views, stored procedures and triggers in enforcing business rules. Discuss their advantages and limitations."],
    [4, 1, 10, "H", "An", "PROBLEM", "CO4", "Normalise the relation ORDER(order_no, date, cust_no, cust_name, item_no, item_desc, qty, price) up to 3NF, stating the functional dependencies at each step."],
    [4, 2, 10, "H", "Ev", "ESSAY", "CO4", "Evaluate the trade-offs between normalisation and denormalisation for a high-volume reporting database."],
    [5, 1, 10, "H", "An", "DESCRIPTIVE", "CO5", "Explain timestamp-ordering and validation-based concurrency control. Compare them with lock-based protocols."],
    [5, 2, 10, "M", "U", "ESSAY", "CO5", "Discuss the ARIES recovery algorithm and its three phases in detail."],
    [1, 2, 10, "M", "U", "ESSAY", "CO1", "Explain the components of a DBMS and the role of each in query processing."],
    [2, 2, 10, "H", "An", "PROBLEM", "CO2", "Express the following queries in tuple relational calculus and relational algebra on a SAILORS–BOATS–RESERVES schema: (a) sailors who reserved a red boat, (b) sailors who reserved all boats. Analyse which formulation is easier to optimise."],
    [3, 1, 10, "M", "Ap", "PROBLEM", "CO3", "Explain correlated and non-correlated subqueries with examples. Rewrite a correlated subquery of your choice as a join and compare performance."],
    [5, 0, 10, "M", "U", "ESSAY", "CO5", "Explain the states of a transaction with a state diagram and discuss how each ACID property is ensured by the DBMS."],
  ],
};

// ───────────────────────── BCS303 Operating Systems ─────────────────────────
export const OPERATING_SYSTEMS: CourseBank = {
  units: [
    { title: "Operating System Fundamentals", topics: ["OS services", "System calls", "OS structures"] },
    { title: "Process Management", topics: ["Processes and threads", "CPU scheduling", "Inter-process communication"] },
    { title: "Synchronisation and Deadlocks", topics: ["Critical section", "Semaphores", "Deadlock handling"] },
    { title: "Memory Management", topics: ["Paging", "Segmentation", "Virtual memory"] },
    { title: "Storage and File Systems", topics: ["Disk scheduling", "File allocation", "Protection"] },
  ],
  outcomes: [
    ["CO1", "Describe the services and structure of operating systems", "UNDERSTAND"],
    ["CO2", "Apply CPU scheduling algorithms", "APPLY"],
    ["CO3", "Analyse synchronisation problems and deadlocks", "ANALYZE"],
    ["CO4", "Apply memory-management techniques", "APPLY"],
    ["CO5", "Evaluate disk scheduling and file-system designs", "EVALUATE"],
  ],
  questions: [
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "Define an operating system."],
    [1, 1, 2, "E", "R", "VERY_SHORT", "CO1", "What is a system call?"],
    [1, 2, 2, "E", "U", "VERY_SHORT", "CO1", "Differentiate between a monolithic kernel and a microkernel."],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "What is a process control block?"],
    [2, 1, 2, "E", "R", "VERY_SHORT", "CO2", "Define turnaround time and waiting time."],
    [2, 0, 2, "E", "U", "VERY_SHORT", "CO2", "Distinguish between a process and a thread."],
    [3, 0, 2, "E", "R", "VERY_SHORT", "CO3", "What is a critical section?"],
    [3, 2, 2, "E", "R", "VERY_SHORT", "CO3", "List the four necessary conditions for deadlock."],
    [3, 1, 2, "E", "R", "VERY_SHORT", "CO3", "What is a binary semaphore?"],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "What is internal fragmentation?"],
    [4, 2, 2, "E", "R", "VERY_SHORT", "CO4", "Define thrashing."],
    [4, 0, 2, "E", "U", "VERY_SHORT", "CO4", "What is the role of the translation look-aside buffer?"],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "Define seek time."],
    [5, 1, 2, "E", "R", "VERY_SHORT", "CO5", "What is contiguous file allocation?"],
    [2, 1, 5, "M", "Ap", "PROBLEM", "CO2", "Compute average waiting time for FCFS and SJF for processes P1–P4 with burst times 6, 8, 7, 3 (all arriving at time 0). Draw the Gantt charts."],
    [2, 2, 5, "M", "U", "DESCRIPTIVE", "CO2", "Explain shared memory and message passing as IPC mechanisms."],
    [1, 0, 5, "E", "R", "DESCRIPTIVE", "CO1", "List and explain the services provided by an operating system."],
    [1, 2, 5, "M", "U", "DESCRIPTIVE", "CO1", "Explain the layered approach to operating-system design."],
    [3, 1, 5, "M", "Ap", "PROBLEM", "CO3", "Solve the producer–consumer problem using semaphores."],
    [3, 2, 5, "M", "U", "DESCRIPTIVE", "CO3", "Explain deadlock prevention methods with examples."],
    [4, 0, 5, "M", "Ap", "PROBLEM", "CO4", "A system has a 32-bit logical address and 4 KB pages. Compute the number of pages and explain address translation."],
    [4, 2, 5, "M", "Ap", "PROBLEM", "CO4", "For the reference string 7, 0, 1, 2, 0, 3, 0, 4, 2, 3 with three frames, count page faults under FIFO and LRU."],
    [5, 0, 5, "E", "U", "DESCRIPTIVE", "CO5", "Explain the SCAN disk-scheduling algorithm with an example."],
    [5, 1, 5, "M", "U", "DESCRIPTIVE", "CO5", "Compare linked and indexed file allocation methods."],
    [1, 1, 10, "M", "U", "ESSAY", "CO1", "Explain the types of system calls with examples and describe how a system call is executed."],
    [2, 1, 10, "H", "Ap", "PROBLEM", "CO2", "Apply Round Robin (quantum 2 ms) and priority scheduling to five processes of your choice. Compare average waiting and turnaround times and comment on starvation."],
    [3, 2, 10, "H", "An", "PROBLEM", "CO3", "Apply the Banker's algorithm to a system with five processes and three resource types (data of your choice) and determine whether the system is in a safe state."],
    [3, 0, 10, "M", "An", "DESCRIPTIVE", "CO3", "Analyse the dining philosophers problem and present a deadlock-free solution using monitors."],
    [4, 2, 10, "H", "An", "DESCRIPTIVE", "CO4", "Explain demand paging and analyse its performance using effective access time. How does thrashing arise and how is it controlled?"],
    [5, 0, 10, "M", "Ev", "PROBLEM", "CO5", "For the request queue 98, 183, 37, 122, 14, 124, 65, 67 with the head at 53, compute head movement for FCFS, SSTF, SCAN and C-LOOK, and evaluate which performs best."],
    [5, 2, 10, "M", "U", "ESSAY", "CO5", "Discuss file-system protection and access-control mechanisms in modern operating systems."],
  ],
};

// ───────────────────────── BCM301 Corporate Accounting ─────────────────────────
export const CORPORATE_ACCOUNTING: CourseBank = {
  units: [
    { title: "Issue of Shares", topics: ["Issue at par and premium", "Forfeiture and reissue", "Underwriting"] },
    { title: "Redemption of Preference Shares and Debentures", topics: ["Redemption of preference shares", "Redemption of debentures"] },
    { title: "Final Accounts of Companies", topics: ["Schedule III format", "Managerial remuneration"] },
    { title: "Valuation of Goodwill and Shares", topics: ["Goodwill valuation", "Share valuation"] },
    { title: "Amalgamation and Internal Reconstruction", topics: ["Purchase consideration", "Internal reconstruction"] },
  ],
  outcomes: [
    ["CO1", "Record transactions relating to issue and forfeiture of shares", "APPLY"],
    ["CO2", "Account for redemption of preference shares and debentures", "APPLY"],
    ["CO3", "Prepare company final accounts as per Schedule III", "APPLY"],
    ["CO4", "Value goodwill and shares using appropriate methods", "ANALYZE"],
    ["CO5", "Evaluate schemes of amalgamation and reconstruction", "EVALUATE"],
  ],
  questions: [
    [1, 0, 2, "E", "R", "VERY_SHORT", "CO1", "What is meant by securities premium?"],
    [1, 1, 2, "E", "R", "VERY_SHORT", "CO1", "Define forfeiture of shares."],
    [1, 2, 2, "E", "R", "VERY_SHORT", "CO1", "What is firm underwriting?"],
    [1, 0, 2, "E", "U", "VERY_SHORT", "CO1", "Distinguish between over-subscription and under-subscription of shares."],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "State any two conditions for redemption of preference shares under the Companies Act, 2013."],
    [2, 1, 2, "E", "R", "VERY_SHORT", "CO2", "What is a sinking fund for redemption of debentures?"],
    [2, 0, 2, "E", "R", "VERY_SHORT", "CO2", "What is the Capital Redemption Reserve?"],
    [3, 0, 2, "E", "R", "VERY_SHORT", "CO3", "What are the two main parts of Schedule III to the Companies Act, 2013?"],
    [3, 1, 2, "E", "R", "VERY_SHORT", "CO3", "What is the overall ceiling on managerial remuneration for a public company?"],
    [4, 0, 2, "E", "R", "VERY_SHORT", "CO4", "Define goodwill."],
    [4, 1, 2, "E", "U", "VERY_SHORT", "CO4", "What is the intrinsic value of a share?"],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "What is purchase consideration in amalgamation?"],
    [5, 1, 2, "E", "U", "VERY_SHORT", "CO5", "Distinguish between external and internal reconstruction."],
    [5, 0, 2, "E", "R", "VERY_SHORT", "CO5", "State the two methods of accounting for amalgamation under AS 14."],
    [1, 0, 5, "M", "Ap", "NUMERICAL", "CO1", "X Ltd issued 10,000 equity shares of ₹10 each at a premium of ₹2, payable ₹3 on application, ₹5 on allotment (including premium) and ₹4 on first and final call. All shares were subscribed and paid. Pass journal entries."],
    [1, 1, 5, "M", "Ap", "NUMERICAL", "CO1", "Y Ltd forfeited 200 shares of ₹10 each (₹8 called up) held by Ram, who paid ₹5 per share. The shares were reissued at ₹7 per share as ₹8 paid up. Pass journal entries and compute the capital reserve."],
    [2, 0, 5, "M", "Ap", "NUMERICAL", "CO2", "Z Ltd redeemed 5,000 10% preference shares of ₹100 each at a premium of 5%, partly out of a fresh issue of equity shares of ₹2,50,000 at par. Pass journal entries."],
    [2, 1, 5, "M", "U", "DESCRIPTIVE", "CO2", "Explain the methods of redemption of debentures."],
    [3, 0, 5, "E", "U", "DESCRIPTIVE", "CO3", "Explain the contents of the Statement of Profit and Loss as per Schedule III."],
    [3, 1, 5, "M", "Ap", "NUMERICAL", "CO3", "From the following, compute the maximum managerial remuneration payable: Net profit before tax ₹40,00,000; depreciation charged ₹2,00,000 (same as Section 123); provision for tax ₹12,00,000 included in expenses."],
    [4, 0, 5, "M", "Ap", "NUMERICAL", "CO4", "Calculate goodwill at three years' purchase of average profits: profits of the last four years were ₹60,000, ₹75,000, ₹90,000 and ₹85,000."],
    [4, 1, 5, "M", "U", "DESCRIPTIVE", "CO4", "Explain the need for valuation of shares and list the factors affecting it."],
    [5, 0, 5, "M", "Ap", "NUMERICAL", "CO5", "A Ltd takes over B Ltd, issuing two shares of ₹10 each at ₹12 for every three shares in B Ltd (30,000 shares) and paying ₹50,000 cash. Compute the purchase consideration."],
    [5, 1, 5, "E", "R", "DESCRIPTIVE", "CO5", "List the steps involved in a scheme of internal reconstruction."],
    [1, 2, 10, "H", "Ap", "NUMERICAL", "CO1", "A Ltd issued 1,00,000 shares, fully underwritten by P, Q and R in the ratio 3:2:1 with firm underwriting of 5,000, 3,000 and 2,000 shares respectively. Marked applications were 30,000, 20,000 and 10,000 and unmarked 20,000. Determine the liability of each underwriter."],
    [2, 1, 10, "M", "Ap", "NUMERICAL", "CO2", "Prepare the Sinking Fund Account, Sinking Fund Investment Account and Debentures Account for three years for debentures of ₹5,00,000 redeemable at par, with an annual instalment of ₹1,50,000 invested at 5%."],
    [3, 0, 10, "M", "Ap", "NUMERICAL", "CO3", "Prepare the Balance Sheet of M Ltd as at 31 March 2026 in the Schedule III format from a trial balance of your construction containing share capital, reserves, long-term borrowings, trade payables, PPE, inventories and trade receivables."],
    [4, 1, 10, "H", "An", "NUMERICAL", "CO4", "From the balance sheet data given below, value an equity share under (a) the net assets method, (b) the yield method and (c) the fair value method.\n\n| Item | ₹ |\n|---|---|\n| Net assets | 12,00,000 |\n| Equity shares of ₹10 | 1,00,000 shares |\n| Average profit after tax | 1,80,000 |\n| Normal rate of return | 12% |"],
    [4, 0, 10, "M", "An", "DESCRIPTIVE", "CO4", "Analyse the different methods of valuation of goodwill with suitable illustrations."],
    [5, 1, 10, "H", "Ev", "NUMERICAL", "CO5", "Pass journal entries for the following scheme of internal reconstruction and prepare the revised balance sheet: equity shares of ₹100 reduced to ₹40, debenture-holders accept 10% sacrifice, goodwill and preliminary expenses written off, and plant revalued downward by ₹60,000."],
    [5, 0, 10, "M", "Ev", "ESSAY", "CO5", "Critically evaluate the pooling-of-interests and purchase methods of accounting for amalgamation."],
  ],
};

/** Light banks for other courses (enough to browse and search; not enough to generate a full paper). */
export const LIGHT_BANKS: Record<string, { units: string[]; questions: [number, number, "E" | "M" | "H", Q[4], QuestionType, string][] }> = {
  BCS501: {
    units: ["Network Fundamentals", "Data Link Layer", "Network Layer", "Transport Layer", "Application Layer"],
    questions: [
      [1, 2, "E", "R", "VERY_SHORT", "Define a computer network and list two of its goals."],
      [1, 5, "M", "U", "DESCRIPTIVE", "Compare the OSI and TCP/IP reference models."],
      [2, 2, "E", "R", "VERY_SHORT", "What is framing in the data link layer?"],
      [2, 5, "M", "Ap", "PROBLEM", "Compute the CRC for the message 1101011011 with generator $x^4 + x + 1$."],
      [3, 10, "H", "An", "PROBLEM", "Explain distance-vector routing and illustrate the count-to-infinity problem."],
      [3, 2, "E", "R", "VERY_SHORT", "What is subnetting?"],
      [4, 5, "M", "U", "DESCRIPTIVE", "Explain TCP connection establishment using the three-way handshake."],
      [5, 10, "M", "U", "ESSAY", "Describe the working of DNS with a suitable example."],
    ],
  },
  BCM302: {
    units: ["Introduction to Statistics", "Measures of Central Tendency", "Measures of Dispersion", "Correlation and Regression", "Index Numbers"],
    questions: [
      [1, 2, "E", "R", "VERY_SHORT", "Define statistics."],
      [2, 5, "M", "Ap", "NUMERICAL", "Calculate the median of 12, 15, 11, 19, 14, 17, 13."],
      [3, 5, "M", "Ap", "NUMERICAL", "Compute the coefficient of variation for the series 20, 25, 30, 35, 40."],
      [4, 10, "H", "Ap", "NUMERICAL", "Compute Karl Pearson's coefficient of correlation for the given data and interpret the result.\n\n| X | 10 | 12 | 14 | 16 | 18 |\n|---|---|---|---|---|---|\n| Y | 40 | 41 | 48 | 60 | 50 |"],
      [5, 2, "E", "R", "VERY_SHORT", "What is an index number?"],
      [5, 10, "M", "An", "NUMERICAL", "Construct Laspeyres' and Paasche's price index numbers for the data provided and comment on the difference."],
    ],
  },
  BBA301: {
    units: ["Foundations of OB", "Individual Behaviour", "Motivation", "Group Dynamics", "Organisational Change"],
    questions: [
      [1, 2, "E", "R", "VERY_SHORT", "Define organisational behaviour."],
      [2, 5, "M", "U", "DESCRIPTIVE", "Explain the Big Five personality model."],
      [3, 10, "M", "An", "ESSAY", "Critically examine Maslow's need hierarchy theory in the Indian workplace."],
      [4, 5, "M", "U", "DESCRIPTIVE", "Explain the stages of group development."],
      [5, 10, "H", "Ev", "CASE_STUDY", "A mid-sized IT firm faces resistance to a new appraisal system. Diagnose the causes and recommend a change-management plan using Lewin's model."],
    ],
  },
  BMA301: {
    units: ["Real Number System", "Sequences", "Series", "Continuity", "Differentiability"],
    questions: [
      [1, 2, "E", "R", "VERY_SHORT", "State the completeness axiom of real numbers."],
      [2, 5, "M", "Ap", "PROBLEM", "Prove that the sequence $a_n = \\frac{n}{n+1}$ converges to 1."],
      [3, 10, "H", "An", "PROBLEM", "Test the convergence of $\\sum_{n=1}^{\\infty} \\frac{n^2}{2^n}$ using the ratio test."],
      [4, 5, "M", "U", "DESCRIPTIVE", "State and prove the intermediate value theorem."],
      [5, 10, "H", "Ap", "PROBLEM", "State Rolle's theorem and verify it for $f(x) = x^2 - 5x + 6$ on $[2, 3]$."],
    ],
  },
  BPH301: {
    units: ["Mechanics of Particles", "Rigid Body Dynamics", "Oscillations", "Gravitation", "Relativity"],
    questions: [
      [1, 2, "E", "R", "VERY_SHORT", "State the law of conservation of linear momentum."],
      [2, 5, "M", "Ap", "NUMERICAL", "Find the moment of inertia of a uniform rod of mass $M$ and length $L$ about an axis through one end."],
      [3, 10, "H", "An", "PROBLEM", "Derive the equation of a damped harmonic oscillator and discuss the under-damped case."],
      [5, 5, "M", "U", "DESCRIPTIVE", "Explain the postulates of the special theory of relativity."],
    ],
  },
};
